# Generated by Django 3.0 on 2019-12-16 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20191213_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='cover_photo',
            field=models.ImageField(default=datetime.datetime(2019, 12, 16, 2, 15, 9, 720967, tzinfo=utc), upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
